# Generated by Django 3.2.6 on 2021-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registereduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='second_name',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name'),
        ),
    ]
