# Generated by Django 3.2.6 on 2021-08-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210827_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('college', models.CharField(max_length=120, verbose_name='College')),
                ('semester', models.IntegerField(verbose_name='Semester')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('event', models.CharField(max_length=120, verbose_name='Event Name')),
            ],
        ),
    ]
